### ISSUE TITLE
Davical, iOS and the auto discovery of available collections

### ISSUE THREAD

**Issue by althaus** [DAViCal/davical#10]
I'm currently investigating an issue with the autodiscovery of available collections on iOS 6. I know that there've been some general issues and I just updated our dev server to the latest 1.1.2 release (replacing 1.0.2).

So the basics are working. I can connect to Davical using domain + username + password. Then Davical is doing it's magic with an `OPTIONS` request followed by a `PROPFIND`. It discovers all collections directly owned by the user like `/caldav/user.name/home`. It does not find any collection the user has access to out of his own principal like:

* `/caldav/other.user/home` granted READ from user to user principal
* `/caldav/group/calendar` granted READ by group membership and WRITE to the user principal
* `/caldav/public/calendar` granted READ to all users and WRITE by the group membership

This has worked in the past, but I don't know when I stopped. I looked into the request send by the device and the only thing I found strange is that it doesn't ask for `calendar-home-set`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <A:add-member/>
    <C:allowed-sharing-modes xmlns:C="http://calendarserver.org/ns/"/>
    <D:bulk-requests xmlns:D="http://me.com/_namespace/"/>
    <E:calendar-color xmlns:E="http://apple.com/ns/ical/"/>
    <B:calendar-description xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:calendar-free-busy-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <E:calendar-order xmlns:E="http://apple.com/ns/ical/"/>
    <B:calendar-timezone xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <A:current-user-privilege-set/>
    <B:default-alarm-vevent-date xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:default-alarm-vevent-datetime xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <A:displayname/>
    <C:getctag xmlns:C="http://calendarserver.org/ns/"/>
    <A:owner/>
    <C:pre-publish-url xmlns:C="http://calendarserver.org/ns/"/>
    <C:publish-url xmlns:C="http://calendarserver.org/ns/"/>
    <C:push-transports xmlns:C="http://calendarserver.org/ns/"/>
    <C:pushkey xmlns:C="http://calendarserver.org/ns/"/>
    <A:quota-available-bytes/>
    <A:quota-used-bytes/>
    <E:refreshrate xmlns:E="http://apple.com/ns/ical/"/>
    <A:resource-id/>
    <A:resourcetype/>
    <B:schedule-calendar-transp xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:schedule-default-calendar-URL xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <C:source xmlns:C="http://calendarserver.org/ns/"/>
    <C:subscribed-strip-alarms xmlns:C="http://calendarserver.org/ns/"/>
    <C:subscribed-strip-attachments xmlns:C="http://calendarserver.org/ns/"/>
    <C:subscribed-strip-todos xmlns:C="http://calendarserver.org/ns/"/>
    <B:supported-calendar-component-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:supported-calendar-component-sets xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <A:supported-report-set/>
    <A:sync-token/>
    <C:xmpp-server xmlns:C="http://calendarserver.org/ns/"/>
    <C:xmpp-uri xmlns:C="http://calendarserver.org/ns/"/>
  </A:prop>
</A:propfind>
```

For comparison I tried aCal and it discovers my own calendar, addressbook and an external binding I tested. I can access the other collections with both apps when I enter the full path manually. So the privileges are correctly handled. I'm pretty sure that iOS could disover those collections in the past (not regarding the WRITE issue group principal thing).

Cheers
Matthias

**Comment by 1358** [comment]
i have the same issue that /caldav/other.user/home is not in the discover-list.
