### ISSUE TITLE
DELETE request

### ISSUE THREAD

**Issue by ikcalB** [DAViCal/davical#35]
When I checked my nginx-logs after setting up davical server (clients: rainloop-webmail, DAVdroid) I encountered the following messages.
(also getting warnings about "application/x-www-form-urlencoded" instead of "text/vcard")

Is this a bug?
(Providing more data, logs as necessary)

/var/log/nginx/err.log:
---------------------------

2015/01/18 19:17:47 [error] 5489#0: *17188 FastCGI sent in stderr: "PHP message: davical: BUG: :Exists true                                                                                
 13 PHP message: ================= Stack Trace ===================                                                                                                                             
 12 PHP message:  ===>  /srv/davical/htdocs/caldav.php[135] calls include()                                                                                                                    
 11 PHP message:  ===>  /srv/davical/inc/caldav-DELETE.php[77] calls do_scheduling_for_delete()                                                                                                
 10 PHP message:  ===>  /srv/davical/inc/schedule-functions.php[32] calls DAVResource->GetProperty()" while reading response header from upstream, client: 10.0.0.200, server: domain.tld, requ    est: "DELETE /caldav/caldav.php/hugendubel/addresses/4ac4bfb5-e850-47a0-8f44-31028471ca27.vcf HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "domain.tld"            
  9 2015/01/18 19:17:47 [error] 5489#0: *17192 FastCGI sent in stderr: "PHP message: davical: BUG: :Exists true                                                                                
  8 PHP message: ================= Stack Trace ===================                                                                                                                             
  7 PHP message:  ===>  /srv/davical/htdocs/caldav.php[135] calls include()                                                                                                                    
  6 PHP message:  ===>  /srv/davical/inc/caldav-DELETE.php[77] calls do_scheduling_for_delete()                                                                                                
  5 PHP message:  ===>  /srv/davical/inc/schedule-functions.php[32] calls DAVResource->GetProperty()" while reading response header from upstream, client: 10.0.0.200, server: domain.tld, requ    est: "DELETE /caldav/caldav.php/hugendubel/addresses/f97e5480-4d77-4f07-a7ad-1bb499b8218f.vcf HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "domain.tld"            
  4 2015/01/18 19:17:47 [error] 5489#0: *17196 FastCGI sent in stderr: "PHP message: davical: BUG: :Exists true                                                                                
  3 PHP message: ================= Stack Trace ===================                                                                                                                             
  2 PHP message:  ===>  /srv/davical/htdocs/caldav.php[135] calls include()                                                                                                                    
  1 PHP message:  ===>  /srv/davical/inc/caldav-DELETE.php[77] calls do_scheduling_for_delete()                                                                                                
15  PHP message:  ===>  /srv/davical/inc/schedule-functions.php[32] calls DAVResource->GetProperty()" while reading response header from upstream, client: 10.0.0.200, server: domain.tld, requ    est: "DELETE /caldav/caldav.php/hugendubel/addresses/53aa2e24-fc47-4f5e-85d6-011660dafe78.vcf HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "domain.tld" 

------------------------

**Comment by althaus** [comment]
Please post your issue at the new location of the DAViCal project:

https://gitlab.com/davical-project/davical
