### ISSUE TITLE
attackers could trick people into believing another upstream version would be current

### ISSUE THREAD

**Issue by calestyo** [DAViCal/davical#4]
Hi.

This is based on: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=703290

While the main point there was fixed in commit 5fccb302a8f326ebab1ae6b4d9599e4ff426b828 another issue with the version check remains open:

We still don't secure the actual string, so an attacker could change it and while the string is encoded now, it may be changed to an old version (e.g. the one the attacked person uses) which is in real however not longer current and contains e.g. an important security whole.
So this would be kinda "downgrade attack" an attacker could do.

The risk is of course only very low, now one should trust such a system anyway.

I see these ways:

1) Secure the version string somehow, either https (which is problematic due to "which CAs are trusted on an arbitrary system"), OpenPGP signature or HMAC.
All of them require some effort to implement.

2) Drop the whole functionality of checking for the current version altogether.
Personally I think, doing update-management from within a software itself is wrong anyway (like they do it on windows in many places).
In UNIX we have distros with systems like apt, or yum which take care upon warnings that new versions are available.

So I'd go for (2), but IMHO Andrew or someone with more authority than I have must decide this eventually.

Cheers,
Chris.

**Comment by calestyo** [comment]
So what has happened to this issue now? Was my request fixed (couldn't find it)? Was the issue re-created at git lab (couldn't find it there either)?

**Comment by althaus** [comment]
I thought all tickets have been re-created at Gitlab? If you feel it's still a concern, please re-open a ticket there.

**Comment by calestyo** [comment]
Ah,.. there is a "page 2" link ... * hiding in some hole * O:-)
